#!/bin/bash -l

#SBATCH -A g2018003
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:0:00 #too long?
#SBATCH -J 5_loop
#SBATCH --mail-type=ALL
#SBATCH --mail-user li120415323@gmail.com

# Load modules
module load bioinfo-tools
module load tophat

# ls SRR604009[2-7]_scaffold_11.1.fastq.gz
ls /home/zhiwei94/Genome-Analysis/analyses/data/RNA_trimmed_data/SRR604009[2-7]_scaffold_11.1.fastq.gz \
| while read forward; do echo $forward; \
reverse=$(echo $forward|sed 's/1.fastq.gz$/2.fastq.gz/');\
echo $reverse;
#sbatch test.sh $forward $reverse;
done
